version: '3.8'

services:
  api:
    build: nestjs
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      PORT: 3000
    ports:
      - "8080:3000"

  postgres:
    image: postgres:14.2
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "champnc" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=champnc
      - POSTGRES_PASSWORD=P@ssw0rd
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=foodjet
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432